name: fresh_harvest
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.9
  fluttericon: ^2.0.0
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  flutter_sticky_header: ^0.6.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/LogoSplashScreen.png
    - assets/images/animlogin.png
    - assets/images/animmulai.png
    - assets/images/TextJudul.png
    - assets/images/bgregister.png
    - assets/images/animberhasil.png
    - assets/images/tombolmulai.png
    - assets/images/animlupasandi.png
    - assets/images/animkodeotp.png
    - assets/images/nav_home.png
    - assets/images/nav_shop.png
    - assets/images/nav_profile.png
    - assets/images/nav_home_on.png
    - assets/images/nav_shop_on.png
    - assets/images/nav_profile_on.png
    - assets/images/posterhome.png
    - assets/images/logoapps.png
    - assets/images/ic_cari.png
    - assets/images/animaturulanglupa.png
    - assets/images/fotoprofil.png
    - assets/images/ic_selesai.png
    - assets/images/ic_dikemas.png
    - assets/images/ic_diambil.png
    - assets/images/ic_proses.png
    - assets/images/ic_message.png
    - assets/images/Alpukat.png
    - assets/images/Jeruk.png
    - assets/images/Pisang.png
    - assets/images/Wortel.png
    - assets/images/Bayam.png
    - assets/images/Cabai.png
    - assets/images/default.png
    - assets/images/fotosaya.jpg
    - assets/images/ApelFuji.png
    - assets/images/maps.png
    - assets/images/icons8-google-480.svg

  fonts:
    - family: Arvo
      fonts:
        - asset: assets/fonts/Arvo-Regular.ttf
        - asset: assets/fonts/Arvo-Bold.ttf
        - asset: assets/fonts/Arvo-BoldItalic.ttf
        - asset: assets/fonts/Arvo-Italic.ttf
          weight: 700

    - family: Chewy
      fonts:
        - asset: assets/fonts/Chewy-Regular.ttf
          weight: 700
flutter_icons:
  remove_alpha_ios: true
  android: true
  ios: true
  image_path: "assets/images/logoapps.png"